force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Bus_Image__c.field-meta.xml
<CustomField>
    <fullName>Bus_Image__c</fullName>
    <formula>IF( ISPICKVAL( Maximum_Capacity__c , &quot;6&quot;),  &quot;/resource/Bus6&quot; ,
(IF( ISPICKVAL( Maximum_Capacity__c , &quot;12&quot;), &quot;/resource/Bus12&quot;,
(IF( ISPICKVAL( Maximum_Capacity__c , &quot;24&quot;), &quot;/resource/Bus24&quot;,
(IF( ISPICKVAL( Maximum_Capacity__c , &quot;36&quot;), &quot;/resource/Bus36&quot;,
(IF( ISPICKVAL( Maximum_Capacity__c , &quot;60&quot;), &quot;/resource/Bus60&quot;,&quot;No Image found&quot; )))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bus Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <label>Odometer Reading</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ListBuses.cls
public with sharing class ListBuses {
    @AuraEnabled //(cacheable=true)
    public static List<Bus__c> getBusList() {
        return [SELECT Id, Name, Year__c, Maximum_Capacity__c, Odometer_Reading__c,Bus_Image__c FROM Bus__c ];
    }
    @AuraEnabled //(cacheable=true)
    public static Bus__c getSingleBus(String recordId){
        return [SELECT Id, Name, Year__c, Maximum_Capacity__c, Odometer_Reading__c,Bus_Image__c FROM Bus__c where Id = :recordId];
    }
}