force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Last_Ping_Location__c.field-meta.xml
<CustomField>
    <fullName>Last_Ping_Location__c</fullName>
    <label>Last Ping Location</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Maintenace_Visit__c.field-meta.xml
<CustomField>
    <fullName>Maintenace_Visit__c</fullName>
    <formula>IF(MOD(Odometer_Reading__c  ,5000) = 0, 0, 1)</formula>
    <label>Maintenace Visit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Garage__c/Garage__c.object-meta.xml
<CustomObject>
    <label>Garage</label>
    <nameField>
        <label>Garage ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <label>Maintenance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Maintenances</relationshipLabel>
    <relationshipName>Maintenances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Garage__c.field-meta.xml
<CustomField>
    <fullName>Garage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garage</label>
    <referenceTo>Garage__c</referenceTo>
    <relationshipLabel>Maintenances</relationshipLabel>
    <relationshipName>Maintenances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NightlyMaintenanceCheck.cls
public with sharing class NightlyMaintenanceCheck implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext ctx){
        return Database.getQueryLocator([SELECT Id,Name,Last_Ping_Location__c FROM Bus__c WHERE Maximum_Capacity__c = '60' AND Maintenace_Visit__c = 0]);
    }
    public void execute(Database.BatchableContext ctx, List<Bus__c> records){
        List<Maintenance__c> maintenanceVisitCreate = new List<Maintenance__c>();
        List<Garage__c> locationGarage = [SELECT Id, Location__c FROM Garage__c];
        for(Bus__c bus:records){
            Location locBus = bus.Last_Ping_Location__c;
            Double minDistance = 0;
            Id garageAssign = null;
            for(Garage__c garage:locationGarage){
                Location locGarage = garage.Location__c;
                if(minDistance == 0){
                    minDistance = locBus.getDistance(locGarage, 'mi');
                }
                else if(minDistance > 0 && locBus.getDistance(locGarage, 'mi') < minDistance){
                    minDistance = locBus.getDistance(locGarage, 'mi');
                    garageAssign = garage.Id;
                }                
            }
            Maintenance__c mvs = new Maintenance__c();
            mvs.Bus__c = bus.Id;
            mvs.Garage__c = garageAssign;
            //mvs.Schedule_Time__c = datetime.now();
            mvs.Name = 'Maintenance required for '+bus.Name+' on '+ Datetime.now().format('yyyy-MM-dd');
            maintenanceVisitCreate.add(mvs);
        }
        Database.insert(maintenanceVisitCreate, false);
    }

    public void finish(Database.BatchableContext ctx){

    }
}